### ISSUE TITLE
Vision Language examples

### ISSUE THREAD

**Issue by AwePhD** [whai362/PVT#101]
Hi, 

Thanks for your great work on Pyramid Vision Transformer. Also, I would be very interested by its applications on Vision Language. In the last commit (5e54cda5c421c7bfb28c77f9890a8c14b36bd7eb) you indicated you have application in Vision Language. Is it an error that there is no link or is it a work in progress? 

Anyway, I am looking forward to read your works on this topic once it's out.

Best regards,
Mathias.

**Comment by DengPingFan** [comment]
Hi,

The paper link: https://dengpingfan.github.io/papers/[2022][MIR]MVLT.pdf
Code: https://github.com/GewelsJI/MVLT
Please check the homepage (https://dengpingfan.github.io/) for more details. 

Best,

**Comment by AwePhD** [comment]
Hi,

Thanks you very much!

Best,
Mathias.
