### ISSUE TITLE
The 'in_channels' in neck and the nn.Conv2d module in net?

### ISSUE THREAD

**Issue by feiyuhuahuo** [whai362/PVT#12]
Hi, I have two questions:
1. The `in_channels` in neck is much smaller than the original RetinaNet. Did you adjust these parameters intentionally？
![图片](https://user-images.githubusercontent.com/32631344/111406558-7d36cc80-870d-11eb-93bf-5c7a18cfd7d8.png)
2. I found there still is `nn.Conv2d` module in the model, so is it a default module in transformer?

**Comment by whai362** [comment]
Hi, thanks for your attention.
1. the `in_channels` is corresponding to the output feature maps' channel of the backbone. Different backbones have different `in_channels`. It is a common setting.
2. `nn.Conv2d` is a convenient implementation of `patch embedding` and `sr`, which also can be implemented by `reshape + nn.Linear`. The two way is completely equivalent, but the first one is more convenient.
