### ISSUE TITLE
Question about pretrained model

### ISSUE THREAD

**Issue by sunnyHelen** [whai362/PVT#13]
Hi, thanks for sharing of your great work. If I change a few layers of your network structure, do I need to retrain on ImageNet to get the pretrained model? Did you compare the performance of models without pretraining?

**Comment by whai362** [comment]
I compared the model with and without pre-trained weights in Figure 5 of our paper, where the conclusion is that the pre-trained weights can help the model converge faster and better.
So if you change a few layers, it would be better to retrain the model on ImageNet.
