### ISSUE TITLE
处理不定长图片的输入

### ISSUE THREAD

**Issue by wuxiaolianggit** [whai362/PVT#15]
大神，您好，这个算法可以处理不定长的图片输入吗？ @whai362 @implus @xieenze

**Comment by whai362** [comment]
可以，具体可以参考检测的backbone
https://github.com/whai362/PVT/blob/main/detection/pvt.py

**Comment by water-wave** [comment]
@whai362 Thank you for your great work.The size of my picture is (256,832),how should I deal with it?Please tell me more details.thanks.
