### ISSUE TITLE
The downsample strides for pvt are different from those in retinanet?

### ISSUE THREAD

**Issue by feiyuhuahuo** [whai362/PVT#16]
Retinanet uses strides=[8, 16, 32, 64, 128], the first stride is 8, but the first stride for pvt is 4 according to the paper. Have you tried the same strides as retinanet for pvt?

**Comment by whai362** [comment]
"Retinanet uses strides=[8, 16, 32, 64, 128]" is for the output of FPN, rather than the backbone output.
The output of PVT-Small has the same strides as that of ResNet50.
Therefore, PVT-Small + FPN also has the same output strides as ResNet50 + FPN.
