### ISSUE TITLE
Question about the drop path in classification model

### ISSUE THREAD

**Issue by YJHMITWEB** [whai362/PVT#2]
Thanks for your great work. When I'm reading your code, I noticed that in main.py, line 379
`model_without_ddp.reset_drop_path(0.0)`
where you manually set the drop path rate to 0, instead of using parser argument.
I'd like to know if this is done intentionally for the classification task, since many related works set the drop path rate to 0.1.
So there are two questions,
1. Why not using parser argument to set it?
2. Are all the results in your paper trained with 0 drop path rate?

Thanks a lot!

**Comment by whai362** [comment]
Hi, thanks for your attention.
PVT-Tiny and PVT-Small use the drop path rate of 0.1.
However, if deeper models (i.e., PVT-Medium and PVT-Large) use 0.1 at the beginning of training, the models will not converge.
So, we set the drop path rate to 0 during the first 100 epochs (warmup), and use 0.1 after 100 epochs.
In addition, reducing the drop path rate of PVT-Medium and PVT-Large is also workable.
