### ISSUE TITLE
training didn't complete after epoch4 

### ISSUE THREAD

**Issue by SamMohel** [whai362/PVT#20]
i used this command for training `python train.py configs/retinanet_pvt_s_fpn_1x_coco_640.py` but got killed here 
`Loading and preparing results...
DONE (t=24.08s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
Killed`
i tried to use resume.sh to complete the process for the last point by using this `./dist_resume.sh /media/user/use/PVT-main/detection/work_dirs/retinanet_pvt_s_fpn_1x_coco_640/epoch_4.pth 1 /media/user/use/PVT-main/detection/checkpoint_root --data-path /media/user/use/PVT-main/coco/` but got 
`Creating model: 1 Traceback (most recent call last): File "main.py", line 442, in <module> main(args) File "main.py", line 251, in main drop_block_rate=None, File "/home/user/anaconda3/lib/python3.7/site-packages/timm/models/factory.py", line 59, in create_model raise RuntimeError('Unknown model (%s)' % model_name) RuntimeError: Unknown model (1) Traceback (most recent call last): File "/home/user/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/home/user/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/user/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module> main() File "/home/user/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main cmd=cmd) subprocess.CalledProcessError: Command '['/home/user/anaconda3/bin/python', '-u', 'main.py', '--model', '1', '--batch-size', '64', '--epochs', '300', '--data-path', '/media/user/use/PVT-main/images', '--output_dir', '/media/user/use/PVT-main/images', '--resume', '/media/user/use/PVT-main/images/checkpoint.pth', '--output_dir', '/media/user/use/PVT-main/output', '--resume', '/media/user/use/PVT-main/detection/work_dirs/retinanet_pvt_s_fpn_1x_coco_640/epoch_3.pth']' returned non-zero exit status 1.`

Did I write or use resume.sh in a false way ?

**Comment by whai362** [comment]
Hi, the training and resuming of the detection models (e.g., RetinaNet) is based on mmdetection. So the training and resuming command should follow mmdetection, such as:
`dist_train.sh configs/retinanet_pvt_s_fpn_1x_coco_640.py 8`
`dist_train.sh configs/retinanet_pvt_s_fpn_1x_coco_640.py 8 --resume XXX`

**Comment by SamMohel** [comment]
excuse me . Does that your email wangwenhai362@smail.nju.edu.cn? can you check it please ?
