### ISSUE TITLE
Training Batch Size on ImageNet

### ISSUE THREAD

**Issue by yaozhewei** [whai362/PVT#21]
In the paper, the training batch size on ImageNet is 128 (I assume it is the entire training batch, e.g. 128 = 8 * 16 (8 GPUs with 16 images each) ). 
However, the dist_train.py uses 128 per GPU, which means the entire batch size is 128 * 8 = 1024. I wonder which one is the correct setting. 

Thanks a lot,

**Comment by whai362** [comment]
mini-batch is 128.
mini b
