### ISSUE TITLE
how can i load pickle file?

### ISSUE THREAD

**Issue by mathshangw** [whai362/PVT#22]
thanks for sharing the code .. i'm trying to load pickle file to read it using these commands 

`import pickle 
infile = open('data.pkl','rb')
new_dict = pickle.load(infile)
infile.close()
print(type(new_dict))`
but error is 
`_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.` 
i searched for the solution but got that  pickle file appears to be using advanced features that suggest it was never supposed to be directly loaded this way. can you help, please ?

**Comment by whai362** [comment]
What is the error code? It seems that there is no 'data.pkl' in this repository.

**Comment by mathshangw** [comment]
thanks for replying , the error is _pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified. i tried to open epoch1 after it finished

**Comment by whai362** [comment]
Could you provide the complete source code and point out the error line?
For example, in XXX line of XXX.py.

**Comment by mathshangw** [comment]
this code what i did 
`import pickle infile = open('data.pkl','rb') new_dict = pickle.load(infile) infile.close() print(type(new_dict))`

and the error in this line `new_dict = pickle.load(infile)` in load function .. i tried to read it by these lines 
`with open('data.pkl', 'rb') as infile:
    content = infile.read()
print(content)`

but got like that `b'\x80\x02}q\x00(X\x04\x00\x00\x00metaq\x01}q\x02(X\r\x00\x00\x00mmdet_versionq\x03X\x06\x00\x00\x002.10.0q\x04X\x07\x00\x00\x00CLASSESq\x05(X\x06\x00\x00\x00personq\x06X\x07\x00\x00\x00bicycleq\x07X\x03\x00\x00\x00carq\x08X\n\x00\x00\x00motorcycleq\tX\x08\x00\x00\x00airplaneq\nX\x03\x00\x00\x00busq\x0bX\x05\x00\x00\x00trainq\x0cX\x05\x00\x00\x00truckq\rX\x04\x00\x00\x00boatq\x0eX\r\x00\x00\x00traffic lightq\x0fX\x0c\x00\x00\x00fire hydrantq\x10X\t\x00\x00\x00stop signq\x11X\r\x00\x00\x00parking meterq\x12X\x05\x00\x00\x00benchq\x13X\x04\x00\x00\x00birdq\x14X\x03\x00\x00\x00catq\x15X\x03\x00\x00\x00dogq\x16X\x05\x00\x00\x00horseq\x17X\x05\x00\x00\x00sheepq\x18X\x03\x00\x00\x00cowq\x19X\x08\x00\x00\x00elephantq\x1aX\x04\x00\x00\x00bearq\x1bX\x05\x00\x00\x00zebraq\x1cX\x07\x00\x00\x00giraffe'

**Comment by whai362** [comment]
There might be a format problem with your `data.pkl`.
As I know, the pickle of py2 and py3 are not compatible.
You could check the document of `pickle`. I have no idea about this.

**Comment by mathshangw** [comment]
Thanks but what is the expected content in the pickle file if I want to
make detection for image .. the objects and their boundaries only

**Comment by mathshangw** [comment]
Thanks but what is the expected content in the pickle file if I want to
make detection for image .. the objects and their boundaries only or where can i find the class of pickle you used as i searched but couldn't find it .. thanks for your time
