### ISSUE TITLE
where can i find your pickle code ?

### ISSUE THREAD

**Issue by mathshangw** [whai362/PVT#23]
what is the expected content in the pickle file if I want to make detection for image .. the objects and their boundaries only or where can i find the class of pickle you used as i searched but couldn't find it .. thanks for your time

**Comment by mathshangw** [comment]
the same problem i got when i tried to open or read pvt_small.pth that has data.pkl file .. Does i read it correctly ?

**Comment by whai362** [comment]
https://github.com/whai362/PVT/blob/f257be19d10af27ac68df946da1e92722a63afe1/main.py#L363

**Comment by SamMohel** [comment]
excuse me i have the same issues i couldn't read .pkl files i got .. if you please how the pickle file was created? does the file include a load persistent ID instruction? or it contains references to data outside the pickle file ?

Thanks a lot for your time

**Comment by SamMohel** [comment]
exucse me i'm trying to open data.pkl in the pvt_small weights but got 
`    raise UnpicklingError("unsupported persistent id encountered")
_pickle.UnpicklingError: unsupported persistent id encountered`
