### ISSUE TITLE
How to decide the learning rate?

### ISSUE THREAD

**Issue by feiyuhuahuo** [whai362/PVT#25]
I found the default lr for mask_rcnn and retinanet are 0.02 and 0.01, respectively. But for retinanet_pvt and mask_rcnn_pvt, the lr are both 0.0001 with AdamW. So how to decide the learning rate, does it depends on the optimizer type or the backbone structure itself? Any advice?

**Comment by whai362** [comment]
https://github.com/whai362/PVT/issues/18#issuecomment-805836597
