### ISSUE TITLE
The img_size is always 224 for object detection task when using different training image size?

### ISSUE THREAD

**Issue by feiyuhuahuo** [whai362/PVT#31]
Since the number of pos_embed parameter depends on the img_size, so do you keep img_size=224 fixed when initiating PVT even when you are training larger images, e.g. RetinaNet with 800+ image size.

**Comment by whai362** [comment]
When making object detection, I use interpolation to adjust the size of pos_embed.
See https://github.com/whai362/PVT/blob/main/detection/pvt.py#L228
