### ISSUE TITLE
The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by SamMohel** [whai362/PVT#33]
i got those lines when tried to train images with this command 
`./dist_train.sh configs/retinanet_pvt_s_fpn_1x_coco_640.py 8` for object detection Task 

`WARNING - The model and loaded state dict do not match exactly
unexpected key in source state_dict: cls_token, norm.weight, norm.bias, head.weight, head.bias`
Does that a normal warning? 

2- Does the weight file for detection here[ https://drive.google.com/file/d/1L5wh2rYsVnuC_CEeFE6yMhU1kENt2gnk/view?usp=sharing ](url)

**Comment by whai362** [comment]
1. `WARNING - The model and loaded state dict do not match exactly unexpected key in source state_dict: cls_token, norm.weight, norm.bias, head.weight, head.bias` is a normal warning.

2. Yes. It is the detection model.

**Comment by 1104662797** [comment]
hello, I get this  command when run `./dist_train.sh configs/retinanet_pvt_t_fpn_1x_coco_640.py 2`:
`missing keys in source state_dict: pos_embed1, pos_embed2, pos_embed3, pos_embed4, patch_embed1.proj.weight, patch_embed1.proj.bias, patch_embed1.norm.weight, patch_embed1.norm.bias, block1.0.norm1.weight, block1.0.norm1.bias, block1.0.attn.q.weight, block1.0.attn.q.bias, block1.0.attn.kv.weight, block1.0.attn.kv.bias, block1.0.attn.proj.weight, block1.0.attn.proj.bias, block1.0.attn.sr.weight, block1.0.attn.sr.bias, block1.0.attn.norm.weight, block1.0.attn.norm.bias, block1.0.norm2.weight, block1.0.norm2.bias, block1.0.mlp.fc1.weight, block1.0.mlp.fc1.bias, block1.0.mlp.fc2.weight, block1.0.mlp.fc2.bias, block1.1.norm1.weight, block1.1.norm1.bias, block1.1.attn.q.weight, block1.1.attn.q.bias, block1.1.attn.kv.weight, block1.1.attn.kv.bias, block1.1.attn.proj.weight, block1.1.attn.proj.bias, block1.1.attn.sr.weight, block1.1.attn.sr.bias, block1.1.attn.norm.weight, block1.1.attn.norm.bias, block1.1.norm2.weight, block1.1.norm2.bias, block1.1.mlp.fc1.weight, block1.1.mlp.fc1.bias, block1.1.mlp.fc2.weight, block1.1.mlp.fc2.bias, patch_embed2.proj.weight, patch_embed2.proj.bias, patch_embed2.norm.weight, patch_embed2.norm.bias, block2.0.norm1.weight, block2.0.norm1.bias, block2.0.attn.q.weight, block2.0.attn.q.bias, block2.0.attn.kv.weight, block2.0.attn.kv.bias, block2.0.attn.proj.weight, block2.0.attn.proj.bias, block2.0.attn.sr.weight, block2.0.attn.sr.bias, block2.0.attn.norm.weight, block2.0.attn.norm.bias, block2.0.norm2.weight, block2.0.norm2.bias, block2.0.mlp.fc1.weight, block2.0.mlp.fc1.bias, block2.0.mlp.fc2.weight, block2.0.mlp.fc2.bias, block2.1.norm1.weight, block2.1.norm1.bias, block2.1.attn.q.weight, block2.1.attn.q.bias, block2.1.attn.kv.weight, block2.1.attn.kv.bias, block2.1.attn.proj.weight, block2.1.attn.proj.bias, block2.1.attn.sr.weight, block2.1.attn.sr.bias, block2.1.attn.norm.weight, block2.1.attn.norm.bias, block2.1.norm2.weight, block2.1.norm2.bias, block2.1.mlp.fc1.weight, block2.1.mlp.fc1.bias, block2.1.mlp.fc2.weight, block2.1.mlp.fc2.bias, patch_embed3.proj.weight, patch_embed3.proj.bias, patch_embed3.norm.weight, patch_embed3.norm.bias, block3.0.norm1.weight, block3.0.norm1.bias, block3.0.attn.q.weight, block3.0.attn.q.bias, block3.0.attn.kv.weight, block3.0.attn.kv.bias, block3.0.attn.proj.weight, block3.0.attn.proj.bias, block3.0.attn.sr.weight, block3.0.attn.sr.bias, block3.0.attn.norm.weight, block3.0.attn.norm.bias, block3.0.norm2.weight, block3.0.norm2.bias, block3.0.mlp.fc1.weight, block3.0.mlp.fc1.bias, block3.0.mlp.fc2.weight, block3.0.mlp.fc2.bias, block3.1.norm1.weight, block3.1.norm1.bias, block3.1.attn.q.weight, block3.1.attn.q.bias, block3.1.attn.kv.weight, block3.1.attn.kv.bias, block3.1.attn.proj.weight, block3.1.attn.proj.bias, block3.1.attn.sr.weight, block3.1.attn.sr.bias, block3.1.attn.norm.weight, block3.1.attn.norm.bias, block3.1.norm2.weight, block3.1.norm2.bias, block3.1.mlp.fc1.weight, block3.1.mlp.fc1.bias, block3.1.mlp.fc2.weight, block3.1.mlp.fc2.bias, patch_embed4.proj.weight, patch_embed4.proj.bias, patch_embed4.norm.weight, patch_embed4.norm.bias, block4.0.norm1.weight, block4.0.norm1.bias, block4.0.attn.q.weight, block4.0.attn.q.bias, block4.0.attn.kv.weight, block4.0.attn.kv.bias, block4.0.attn.proj.weight, block4.0.attn.proj.bias, block4.0.norm2.weight, block4.0.norm2.bias, block4.0.mlp.fc1.weight, block4.0.mlp.fc1.bias, block4.0.mlp.fc2.weight, block4.0.mlp.fc2.bias, block4.1.norm1.weight, block4.1.norm1.bias, block4.1.attn.q.weight, block4.1.attn.q.bias, block4.1.attn.kv.weight, block4.1.attn.kv.bias, block4.1.attn.proj.weight, block4.1.attn.proj.bias, block4.1.norm2.weight, block4.1.norm2.bias, block4.1.mlp.fc1.weight, block4.1.mlp.fc1.bias, block4.1.mlp.fc2.weight, block4.1.mlp.fc2.bias
`


I have retrained the PVT_tiny, I could load model in classification task, i have check the keys of state dict in my trained model, I get this `>>> state_dict.keys()
dict_keys(['model', 'optimizer', 'lr_scheduler', 'epoch', 'scaler', 'args'])` .
 **In the "model" I got the miss keys, I want to know what can i do  to fix this bug in detection**

**Comment by devashish-bhake** [comment]
> hello, I get this command when run `./dist_train.sh configs/retinanet_pvt_t_fpn_1x_coco_640.py 2`: `missing keys in source state_dict: pos_embed1, pos_embed2, pos_embed3, pos_embed4, patch_embed1.proj.weight, patch_embed1.proj.bias, patch_embed1.norm.weight, patch_embed1.norm.bias, block1.0.norm1.weight, block1.0.norm1.bias, block1.0.attn.q.weight, block1.0.attn.q.bias, block1.0.attn.kv.weight, block1.0.attn.kv.bias, block1.0.attn.proj.weight, block1.0.attn.proj.bias, block1.0.attn.sr.weight, block1.0.attn.sr.bias, block1.0.attn.norm.weight, block1.0.attn.norm.bias, block1.0.norm2.weight, block1.0.norm2.bias, block1.0.mlp.fc1.weight, block1.0.mlp.fc1.bias, block1.0.mlp.fc2.weight, block1.0.mlp.fc2.bias, block1.1.norm1.weight, block1.1.norm1.bias, block1.1.attn.q.weight, block1.1.attn.q.bias, block1.1.attn.kv.weight, block1.1.attn.kv.bias, block1.1.attn.proj.weight, block1.1.attn.proj.bias, block1.1.attn.sr.weight, block1.1.attn.sr.bias, block1.1.attn.norm.weight, block1.1.attn.norm.bias, block1.1.norm2.weight, block1.1.norm2.bias, block1.1.mlp.fc1.weight, block1.1.mlp.fc1.bias, block1.1.mlp.fc2.weight, block1.1.mlp.fc2.bias, patch_embed2.proj.weight, patch_embed2.proj.bias, patch_embed2.norm.weight, patch_embed2.norm.bias, block2.0.norm1.weight, block2.0.norm1.bias, block2.0.attn.q.weight, block2.0.attn.q.bias, block2.0.attn.kv.weight, block2.0.attn.kv.bias, block2.0.attn.proj.weight, block2.0.attn.proj.bias, block2.0.attn.sr.weight, block2.0.attn.sr.bias, block2.0.attn.norm.weight, block2.0.attn.norm.bias, block2.0.norm2.weight, block2.0.norm2.bias, block2.0.mlp.fc1.weight, block2.0.mlp.fc1.bias, block2.0.mlp.fc2.weight, block2.0.mlp.fc2.bias, block2.1.norm1.weight, block2.1.norm1.bias, block2.1.attn.q.weight, block2.1.attn.q.bias, block2.1.attn.kv.weight, block2.1.attn.kv.bias, block2.1.attn.proj.weight, block2.1.attn.proj.bias, block2.1.attn.sr.weight, block2.1.attn.sr.bias, block2.1.attn.norm.weight, block2.1.attn.norm.bias, block2.1.norm2.weight, block2.1.norm2.bias, block2.1.mlp.fc1.weight, block2.1.mlp.fc1.bias, block2.1.mlp.fc2.weight, block2.1.mlp.fc2.bias, patch_embed3.proj.weight, patch_embed3.proj.bias, patch_embed3.norm.weight, patch_embed3.norm.bias, block3.0.norm1.weight, block3.0.norm1.bias, block3.0.attn.q.weight, block3.0.attn.q.bias, block3.0.attn.kv.weight, block3.0.attn.kv.bias, block3.0.attn.proj.weight, block3.0.attn.proj.bias, block3.0.attn.sr.weight, block3.0.attn.sr.bias, block3.0.attn.norm.weight, block3.0.attn.norm.bias, block3.0.norm2.weight, block3.0.norm2.bias, block3.0.mlp.fc1.weight, block3.0.mlp.fc1.bias, block3.0.mlp.fc2.weight, block3.0.mlp.fc2.bias, block3.1.norm1.weight, block3.1.norm1.bias, block3.1.attn.q.weight, block3.1.attn.q.bias, block3.1.attn.kv.weight, block3.1.attn.kv.bias, block3.1.attn.proj.weight, block3.1.attn.proj.bias, block3.1.attn.sr.weight, block3.1.attn.sr.bias, block3.1.attn.norm.weight, block3.1.attn.norm.bias, block3.1.norm2.weight, block3.1.norm2.bias, block3.1.mlp.fc1.weight, block3.1.mlp.fc1.bias, block3.1.mlp.fc2.weight, block3.1.mlp.fc2.bias, patch_embed4.proj.weight, patch_embed4.proj.bias, patch_embed4.norm.weight, patch_embed4.norm.bias, block4.0.norm1.weight, block4.0.norm1.bias, block4.0.attn.q.weight, block4.0.attn.q.bias, block4.0.attn.kv.weight, block4.0.attn.kv.bias, block4.0.attn.proj.weight, block4.0.attn.proj.bias, block4.0.norm2.weight, block4.0.norm2.bias, block4.0.mlp.fc1.weight, block4.0.mlp.fc1.bias, block4.0.mlp.fc2.weight, block4.0.mlp.fc2.bias, block4.1.norm1.weight, block4.1.norm1.bias, block4.1.attn.q.weight, block4.1.attn.q.bias, block4.1.attn.kv.weight, block4.1.attn.kv.bias, block4.1.attn.proj.weight, block4.1.attn.proj.bias, block4.1.norm2.weight, block4.1.norm2.bias, block4.1.mlp.fc1.weight, block4.1.mlp.fc1.bias, block4.1.mlp.fc2.weight, block4.1.mlp.fc2.bias `
> 
> I have retrained the PVT_tiny, I could load model in classification task, i have check the keys of state dict in my trained model, I get this `>>> state_dict.keys() dict_keys(['model', 'optimizer', 'lr_scheduler', 'epoch', 'scaler', 'args'])` . **In the "model" I got the miss keys, I want to know what can i do to fix this bug in detection**

I am having the same exact error have you found any solution for that yet?
