### ISSUE TITLE
KeyError: 'meta' in testing

### ISSUE THREAD

**Issue by SamMohel** [whai362/PVT#34]
i was trying to test the model by this command 

`python test.py /home/user/Desktop/PVT-main/detection/configs/retinanet_pvt_s_fpn_1x_coco_640.py /home/user/Desktop/PVT-main/pretrained/pvt_small.pth  --show-dir /home/user/Desktop/results.pkl `

and got this warning , this is part of the warning as it is more than 10 lines 
`unexpected key in source state_dict: pos_embed1, pos_embed2, pos_embed3, pos_embed4, cls_token, patch_embed1.proj.weight, patch_embed1.proj.bias, patch_embed1.norm.weight, patch_embed1.norm.bias, patch_embed2.proj.weight, patch_embed2.proj.bias, patch_embed2.norm.weight, patch_embed2.norm.bias, patch_embed3.proj.weight, `

then give this error 
`Traceback (most recent call last):`
 ` File "test.py", line 213, in <module>`
    `main()`
 ` File "test.py", line 175, in main`
    `if 'CLASSES' in checkpoint['meta']:`
`KeyError: 'meta'`

**Comment by whai362** [comment]
`pvt_small.pth` is classification model.
Maybe you could replace it with https://drive.google.com/file/d/1L5wh2rYsVnuC_CEeFE6yMhU1kENt2gnk/view?usp=sharing, which can be found at https://github.com/whai362/PVT/blob/main/detection/README.md.
