### ISSUE TITLE
semantic segmentation code

### ISSUE THREAD

**Issue by hgmlu** [whai362/PVT#35]
Hi,thaks for your excellent work!!!
I have read your paper named 'Pyramid Vision Transformer: A Versatile Backbone for Dense Prediction without Convolutions', and want to apply it in my work in semantic segmentation,  When will you make the semantic segmentation code and models public?

**Comment by whai362** [comment]
Thanks for your attention.
Segmentation models will be given by @xieenze.
But we are catching DDL recently, we try to release segmentation models in three weeks.

**Comment by SamMohel** [comment]
@whai362 excuse me can you see your mail? Thanks

**Comment by hgmlu** [comment]
Thanks for your reply! Look forward for your semantic segmentation  models!

**Comment by ShihuaHuang95** [comment]
Waiting for the semantic segmentation code, too.

**Comment by choodly** [comment]
Waiting for the semantic segmentation code, too.

**Comment by xieenze** [comment]
Hi all, 
Thanks for your attention to it.
We will release it asap after NeurIPS DDL. Sorry for the wait!

**Comment by xieenze** [comment]
Hi all,
Thanks for the patient waiting! 
We have released the code, log, and model for PVT on semantic segmentation.
It is surprising that the result in our code is higher than that in the paper.

**Comment by hgmlu** [comment]
thanks for you sharing！！！
