### ISSUE TITLE
pvt_small is not in the backbone registry

### ISSUE THREAD

**Issue by mathshangw** [whai362/PVT#36]
i got this error  `raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "RetinaNet: 'pvt_small is not in the backbone registry'"` when I used `python train.py configs/retinanet_pvt_s_fpn_1x_coco_640.py`

**Comment by whai362** [comment]
Hi, do you `import pvt` in your train.py?
We have registered `pvt_small` at line #312 in https://github.com/whai362/PVT/blob/main/detection/pvt.py.
