### ISSUE TITLE
代码方面的问题

### ISSUE THREAD

**Issue by qdd1234** [whai362/PVT#38]
您好，关于PVT的代码一些问题我想向您请教一下
![Uploading image.png…]()
我图中第二个注释表明我的代码运行出错的地方，我想问一下是我这边代码拷贝错误还是您当时代码上传有误？谢谢

**Comment by whai362** [comment]
抱歉最近有些忙。你的图片好像失效了我看不到，可以麻烦重新指出一下吗？
