### ISSUE TITLE
what is the difference between pvt here?

### ISSUE THREAD

**Issue by mathshangw** [whai362/PVT#40]
https://github.com/whai362/PVT/blob/main/pvt.py 

https://github.com/whai362/PVT/blob/main/detection/pvt.py 

2- does 12 epochs for detection and 300 epochs for classification ?

**Comment by whai362** [comment]
Hi，the first one is for classification.
The second one is for detection.
You could follows the command in readme to train/test models.

**Comment by mathshangw** [comment]
Excuse me why there is different epochs like 12 and 300? What is the difference ?
