### ISSUE TITLE
which one for detection ?

### ISSUE THREAD

**Issue by mathshangw** [whai362/PVT#41]
1- which one pre-trained i should use for object detection??
https://drive.google.com/file/d/1L5wh2rYsVnuC_CEeFE6yMhU1kENt2gnk/view?usp=sharing 
or 
https://drive.google.com/file/d/1vtcyoU8KUqNzktlMGXZrYcMRsNNiVZFQ/view?usp=sharing

**Comment by whai362** [comment]
Hi，the first one is a model of retinanet.
The second one is the pretrained weights of the backbone of retinanet.
If you want to train a model，you need to load the second pretrained model.
If you just want to test the object detector，you could load the first one，and test on mscoco val2017.
