### ISSUE TITLE
PVT DETR?

### ISSUE THREAD

**Issue by zobeirraisi** [whai362/PVT#42]
Can you please update the model and config for detr+pvt?
I get an error when I want to train on this config?

**Comment by whai362** [comment]
We have updated the detr + pvt to the mmdet 2.13.0 。
https://github.com/whai362/PVT/blob/v2/detection/configs/detr_pvt_s_8x2_50ep_coco.py
We also update pvtv2, which works much better than pvt.

**Comment by Patrickctyyx** [comment]
> We have updated the detr + pvt to the mmdet 2.13.0 。
> [https://github.com/whai362/PVT/blob/v2/detection/configs/detr_pvt_s_8x2_50ep_coco.py](https://github.com/whai362/PVT/blob/v2/detection/configs/detr_pvt_s_8x2_50ep_coco.py?rgh-link-date=2021-06-23T14%3A25%3A05Z)
> We also update pvtv2, which works much better than pvt.

Hello, is PVTv2 DETR available now?
