### ISSUE TITLE
Visualize PVT detection?

### ISSUE THREAD

**Issue by zobeirraisi** [whai362/PVT#47]
How can we visualize the trained models? Is there any demo?
Thanks

**Comment by whai362** [comment]
Thanks for your attention!
You could use the ``analyze_results.py'' of mmdetection to visualize the detection results.
We also provide a similar code at https://github.com/whai362/PVT/blob/v2/detection/analyze_results.py
More detail can be found at https://github.com/open-mmlab/mmdetection/blob/master/docs/useful_tools.md

**Comment by zobeirraisi** [comment]
Thanks for your reply, I mean how to inference a single image?

**Comment by whai362** [comment]
We will try to provide a single-image demo later.

**Comment by whai362** [comment]
> Thanks for your reply, I mean how to inference a single image?
We provide a demo.py at 
https://github.com/whai362/PVT/blob/v2/detection/demo.py
