### ISSUE TITLE
Repeated Key Improvements

### ISSUE THREAD

**Issue by BebDong** [whai362/PVT#48]
The three key improvements of PVT2 are seemingly a direct copy from the next-door [SegFormer](https://arxiv.org/abs/2105.15203).

**Comment by whai362** [comment]
Thanks for your attention!
(1) SegFormer has no Linear SRA. Please check the paper carefully.
(2) PVT, PVTv2, and SegFormer are a series of research works from one team, not **next-door**.
(3) PVTv2 is just an experimental report, which summarizes the techniques in our recent works.

**Comment by xieenze** [comment]
@whai362 's opinion is exactly correct. We are co-authors of these three papers.
Sorry to make @BebDong confuse, but he has a misunderstanding of these papers.
PVTv2 is a experimental report to show how to improve PVT being a better backbone.
