### ISSUE TITLE
classification-pvt load finetune model error

### ISSUE THREAD

**Issue by zcc720** [whai362/PVT#49]
`        if 'model' in checkpoint:
            model_without_ddp.load_state_dict(checkpoint['model'])
        else:
            model_without_ddp.load_state_dict(checkpoint)`

  File "main.py", line 271, in main
    model_without_ddp.load_state_dict(checkpoint)
UnboundLocalError: local variable 'model_without_ddp' referenced before assignment

**Comment by whai362** [comment]
Can you provide your command？

**Comment by whai362** [comment]
I fix the bug.
Thanks for your reminder.
