### ISSUE TITLE
Grad strides do not match bucket view strides

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [whai362/PVT#51]
hi when i use it as backbone to train a classifier, i meet the problem 'Grad strides do not match bucket view strides'. it seems transpose causes the gradients stride wrong. Need to be contigous.

**Comment by whai362** [comment]
We have not met this problem.
Could you point out the line that needs to be contigous?

**Comment by zimenglan-sysu-512** [comment]
hi @whai362 
this line: https://github.com/whai362/PVT/blob/v2/classification/pvt_v2.py#L308
