### ISSUE TITLE
Pretrained model error

### ISSUE THREAD

**Issue by VietDunghacker** [whai362/PVT#52]
When I load the pretrained weights of Sparse R-CNN with PVT-b2 backbone, it showed this error: "RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory". I believe the file was not saved correctly.

**Comment by xieenze** [comment]
Hi @VietDunghacker 
Maybe the checkpoint had some problem when I upload from my server to google drive.
You can try to train it by yourself, the coco training result is very stable and I believe you can re-implement our results.
We will also re-train a model and release it recently.

**Comment by czczup** [comment]
@VietDunghacker 
Hi, we updated the weight of Sparse R-CNN with PVT-b2 backbone [[link]](https://drive.google.com/file/d/1xtn-wD_nYSwudF1SqsSHl7opEXM4dhPN/view?usp=sharing).
