### ISSUE TITLE
misaligned experimental results

### ISSUE THREAD

**Issue by memorywxy** [whai362/PVT#53]
Hi there, thx for the sharing. 
I found two problems:
1) The reported image classification performance for Twins-SVT-L ([https://github.com/Meituan-AutoML/Twins]) on ImageNet-1K using 224x224 scales was 83.7, but in your paper it's 83.3, why is that?
2) You compared large models PVTv2-B4/B5 with Swin-S and Swin-B for image classification,  but the corresponding comparisons were missing for object detection and segmentation, could you elaborate more?

**Comment by whai362** [comment]
Hi, thanks for your attention.
(1) twins-L is 83.3 in its old paper (https://arxiv.org/pdf/2104.13840v1.pdf). We will update the new result (83.7) in our revised version later.
(2) Yes we will report more results.
