### ISSUE TITLE
some warnings

### ISSUE THREAD

**Issue by cuixing61** [whai362/PVT#54]
hi, when i tried to train the model by myself, lots of warning appeared.
UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
although these warnings seems no harm when training the model

**Comment by whai362** [comment]
Yes, there are some warnings, but these warnings are not harmful to the model.
