### ISSUE TITLE
Broken links  for image classification checkpoints 

### ISSUE THREAD

**Issue by giladsharir** [whai362/PVT#56]
The links for pretrained PVTv2 on ImageNet-1K seem to be not working. 
I could only access PVT-V2-B2-Linear 
Thanks

**Comment by whai362** [comment]
Hi, which link? Could you provide url?

**Comment by whai362** [comment]
Google Drive: https://drive.google.com/file/d/1snw4TYUCD5z4d3aaId1iBdw-yUKjRmPC/view
github: https://github.com/whai362/PVT/releases/download/v2/pvt_v2_b2.pth

**Comment by giladsharir** [comment]
thanks, 
the links from google drive don't open, 
but the links from github https://github.com/whai362/PVT/releases/  seem to be ok.
