### ISSUE TITLE
why SRA linear is set False in V2?

### ISSUE THREAD

**Issue by Darknesszlx** [whai362/PVT#58]
https://github.com/whai362/PVT/blob/ae66037b5a7b2cede27fc9f068f811f0f93504a3/classification/pvt_v2.py#L216

https://github.com/whai362/PVT/blob/ae66037b5a7b2cede27fc9f068f811f0f93504a3/classification/pvt_v2.py#L327-L332

**Comment by whai362** [comment]
We provide pvtv2 with linear SRA at https://github.com/whai362/PVT/blob/v2/classification/pvt_v2.py#L392 .
