### ISSUE TITLE
model complexity

### ISSUE THREAD

**Issue by Xyxy1722** [whai362/PVT#60]
Thanks for your great work.
When I trained pvt_v2_b0, I found that the number of parameters of  it was 3666760 in training log. However, in paper you submitted it is only 3.4M. Have you made small changes to the model? If so, could you share the small changes?  Thanks a lot.

**Comment by czczup** [comment]
@Xyxy1722 
Thanks for your careful examination. The correct number of parameters of pvt_v2_b0 is 3.7M. We have updated the README, and we will fix this error in the paper.
