### ISSUE TITLE
Difference between 3x_mstrain vs. 1x_coco in detection

### ISSUE THREAD

**Issue by youngwanLEE** [whai362/PVT#61]
Hi, I'm impressed by your excellent work.

I have a question.

It seems that the optimizer settings of [1x_coco](https://github.com/whai362/PVT/blob/v2/detection/configs/mask_rcnn_pvt_v2_b2_fpn_1x_coco.py
) are different from [3x_mstrain](https://github.com/whai362/PVT/blob/v2/detection/configs/mask_rcnn_pvt_v2_b2_fpn_3x_mstrain.py) for mask_rcnn.

For examples,

|model|lr|weight decay |
|---|---|---|
|1x_coco|0.0002|0.0001|
|3x_ms|0.0001|0.05|

It seems the 3x_ms setting follows [Swin-Transformer settings](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_1x_coco.py#L64-L67).

Is there a reason why you set this differently?

**Comment by whai362** [comment]
Yes, we try to make a fair comparison with swin.
Thanks for your attention.

**Comment by youngwanLEE** [comment]
@whai362 Thanks for reply :)
