### ISSUE TITLE
About `patch_size` in pvt_v2

### ISSUE THREAD

**Issue by abhi-glitchhg** [whai362/PVT#72]
Hey there! 
I read your paper and have gone through the code; amazing work!

While going through the code I noticed that we are not using  `patch_size` variable  in  PyramidVisionTransformerV2 class; 
`patch_size` is either 7 or 3; but we are not using `patch_size` variable anywhere in the class [Link](https://github.com/whai362/PVT/blob/v2/classification/pvt_v2.py#L227)

But in many `register_model` decorators, you have used `patch_size` as 4  [link](https://github.com/whai362/PVT/blob/v2/classification/pvt_v2.py#L326) 

So whether V2 is always supposed to use 7 for first stage and 3 for the rest stages; 

Could you clarify this?

**Comment by czczup** [comment]
> Hey there! I read your paper and have gone through the code; amazing work!
> 
> While going through the code I noticed that we are not using `patch_size` variable in PyramidVisionTransformerV2 class; `patch_size` is either 7 or 3; but we are not using `patch_size` variable anywhere in the class [Link](https://github.com/whai362/PVT/blob/v2/classification/pvt_v2.py#L227)
> 
> But in many `register_model` decorators, you have used `patch_size` as 4 [link](https://github.com/whai362/PVT/blob/v2/classification/pvt_v2.py#L326)
> 
> So whether V2 is always supposed to use 7 for first stage and 3 for the rest stages;
> 
> Could you clarify this?

Hi, please refer to this code: [link](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/pvt.py)
The patch_size of pvtv2 is [7, 3, 3, 3], the `patch_size=4` is unused, we will fix this.

**Comment by abhi-glitchhg** [comment]
Great thanks! Will look into the code
