### ISSUE TITLE
problems about loading pretrained model with pytorch version below 1.6

### ISSUE THREAD

**Issue by WxWstranger** [whai362/PVT#8]
problems about loading pretrained model with pytorch version below 1.6

pytorch 1.6 have switched torch.save to use a zip file-based format by default rather than the old Pickle-based format. This cause pytorchs with version below 1.6 can not load the pretained models AT ALL. 

Can you use "_use_new_zipfile_serialization=False" when using torch.save()?  just like torch.save(m.state_dict(), 'mymodel.pt', _use_new_zipfile_serialization=False). And provide another version of pretrained models?

Thanks a lot!!!!

**Comment by whai362** [comment]
Thanks for your suggestion. We will prepare weights for pytorch<1.5.

**Comment by WxWstranger** [comment]
Thank you so much, bro.

**Comment by whai362** [comment]
Weights for pytorch<1.5 are available.
