### ISSUE TITLE
pvt-v2 for segmentation tasks

### ISSUE THREAD

**Issue by zijunwei** [whai362/PVT#86]
Hi, do you have pvt-v2 pretrained models for segmentation tasks?
How is pvt-v2 backbone different than segformer backbone?
It seems to be pvt-v2-linear are using average pooling, but all other variants seem to be the same as segfomer backbone?

**Comment by whai362** [comment]
Hi, thanks for your attention.
See here.
https://github.com/whai362/PVT/issues/48#issuecomment-870253269

**Comment by whai362** [comment]
pvt-v2 + segmentation see here https://github.com/whai362/PVTv2-Seg
