### ISSUE TITLE
question for PVTv2: in the paper the reduction ratio is 7 in Linear SRA, but in the code  is sr_ratios=[8, 4, 2, 1]

### ISSUE THREAD

**Issue by StormArcher** [whai362/PVT#90]
question for PVTv2: in the paper the reduction ratio is 7 in Linear SRA, but in the code  is sr_ratios=[8, 4, 2, 1],

Is there something wrong with my understanding?

**Comment by whai362** [comment]
Hi, 7 is the attention pooling window size of PVTv2-Li. In "*-Li" models, sr_ratios are not available.

![image](https://user-images.githubusercontent.com/8529570/147643925-275c5806-e283-4fe1-91cf-3ea800f041fe.png)

**Comment by whai362** [comment]
See "7" at here: https://github.com/whai362/PVT/blob/v2/classification/pvt_v2.py#L77

**Comment by StormArcher** [comment]
Thank you . &nbsp;Very nice idea. &nbsp;Thanks for you response


发自我的iPhone


------------------ Original ------------------
From: whai362 ***@***.***&gt;
Date: Wed,Dec 29,2021 4:49 PM
To: whai362/PVT ***@***.***&gt;
Cc: Archerzjc ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [whai362/PVT] question for PVTv2: in the paper the reduction ratio is 7 in Linear SRA, but in the code  is sr_ratios=[8, 4, 2, 1] (Issue #90)





 
Hi, 7 is the attention pooling window size of PVTv2-Li. In "*-Li" models, sr_ratios are not available.
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
